<?php
// Kyberia senate specific settings (special node numbers, etc)

// logout after two hours
define('LOGOUT_IDLE_SEC',		7200);

// An attempt to remove hard-code constants from code
define('DEFAULT_NODE_ID',		1);
define('DEFAULT_TEMPLATE_ID',		4);

define('UBIK_ID',			332);
define('DEFAULT_LISTING_AMOUNT',	32);

define('DAILY_K',			30);
define('REGISTRATION_VOTES',		2);

define('MAIL_NODE',			24);
define('REGISTRATION_TEXT_NODE',	791946);
define('REGISTRATION_REQUEST_NODE',	2091448);
define('UNVERIFIED_REGISTRATIONS_NODE',	1836516);

define('DEF_DATA_TEMPLATE',		12);
define('DEF_GALLERY_TEMPLATE',		1041658);
define('DEF_LAST_NODE',			23);

define('DEF_LISTING_AMMOUNT',		42);
define('DEF_MAX_LISTING_AMMOUNT',	333);
define('DEF_MAX_GET_THREADED_CHILDREN',	100);

?>
